<a href="https://colab.research.google.com/github/sgr1118/PyTorch/blob/main/Chapter03_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EB%93%80%ED%86%A0%EB%A6%AC%EC%96%BC_ipynp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 3.4 텐서 기본 연산



In [ ]:
# 토치 불러오기

import torch

### 1. 요소별 산술 연산

a = [1 2  
     3 4]

b = [2 2  
     3 3]
는 다음과 같이 파이썬 코드로 나타낼 수 있다.

In [ ]:
a = torch.FloatTensor([[1,2], [3,4]])

b = torch.FloatTensor([[2,2], [3,3]])

In [ ]:
# 행렬 덧셈

a + b

tensor([[3., 4.],
        [6., 7.]])

In [ ]:
# a-b
print(a-b)

# a * b
print(a*b)

# a / b
print(a/b)

# a**b
print(a**b)

# a == b
print(a == b)

# a != b
print(a != b)

tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
tensor([[ 1.,  4.],
        [27., 64.]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])


### 2. 인플레이스 연산

- 앞에서 수행한 연산들의 결과 텐서는 메모리에 새롭게 할당됩니다. 빈 메모리의 공간에 결과 텐서가 할당되고 결과 텐서의 값이 위치하게 되는 것입니다. 하지만 지금부터 설명할 인플레이스 연산은 같은 산술 연산을 수행하지만 기존 텐서에 결과과 저장된다는 차이점이 있습니다.

In [ ]:
# a.mul(b)의 연산 결과

print(a.mul(b))

# a 출력해보기

print(a)

# a.mul의 연산 결과는 새로운 메모리에 할당되기 때문에 텐서 a를 출력하면 값은 그대로이다.

tensor([[  8.,  16.],
        [ 81., 108.]])
tensor([[ 4.,  8.],
        [27., 36.]])


In [ ]:
# 인플레이스 연산들은 밑줄이 함수명 뒤에 붙어있는 것이 특징이다.
# 따라서 곱셈 함수의 인플레이스 연산 함수는 mul_()으로 대응된다.

print(a.mul_(b))

print(a)

tensor([[ 4.,  8.],
        [27., 36.]])
tensor([[ 4.,  8.],
        [27., 36.]])


### 3. 차원 축소 연산 : 합과 평균

X = [[1 2] 
     [3 4]]
다음과 같은 텐서 X가 있다고 가정한다.

In [ ]:
x = torch.FloatTensor([[1,2], [3,4]])

In [ ]:
# dim = 0이면 첫 번째 차원을 이야기하는 것이므로 행렬의 세로축에 대해서 합 연산을 수행합니다.
# 수식으로 표현하면 다음과 가이 표현될 수 있다. 수식에서 T표시는 행렬과 열을 바꿔 표현하는 전치 연산을 의미한다.

print(x.sum(dim=0)) # 1 + 3, 2 + 4로 전치 연산이 수행됨


print(x.sum(dim=-1)) # 1+2, 3+4로 연산 수행
# dim = -1은 뒤에서 첫 번째 차원을 의미한다. 여기는 2개의 차원만 존재하기 때문에 dim = 1을 넣어준것과 같은 의미이다.

tensor([4., 6.])
tensor([3., 7.])


### 4. 브로드캐스트 연산
이전까지의 산술 연산들은 두 텐서의 크기가 같은 경우를 예시로 들었다. 그럼 크기가 다른 두 텐서를 가지고 산술 연산을 수행하면 어떻게 될까?

In [ ]:
# 텐서 + 스칼라
# 행렬 x의 각 요소에 모두 1이 더해진 것을 볼 수 있다. 

x = torch.FloatTensor([[1,2], [3,4]])
y = 1

z = x + y

print(z, z.size())

tensor([[2., 3.],
        [4., 5.]]) torch.Size([2, 2])


In [ ]:
# 텐서 + 벡터

x = torch.FloatTensor([[1,2], [4,8]])

y = torch.FloatTensor([3, 
                       5])

print(x.size(), y.size())

z = x+y

print(z, z.size())

torch.Size([2, 2]) torch.Size([2])
tensor([[ 4.,  7.],
        [ 7., 13.]]) torch.Size([2, 2])


In [ ]:
# 텐서 + 텐서

x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3, 
                       5])

print(x.size(), y.size())

z = x+y
print(z, z.size())

torch.Size([1, 1, 2]) torch.Size([2])
tensor([[[4., 7.]]]) torch.Size([1, 1, 2])


## 3.5 텐서 형태 변환
텐서의 전체 요소 개수는 유지한 채 모양을 바꾸는 방법을 알아보겠습니다.

### 1.View 함수

In [ ]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])

print(x.size())

print(x.view(12))

print(x.view(3,4))

print(x.view(3, 1, 4))

torch.Size([3, 2, 2])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


만약 새로운 크기의 기존 텐서의 요소 개수와 맞지 않으면 오류가 발생한다. 하지만 view 함수에 인자를 넣어줄 때 -1을 활용하면 일일이 요소 개수를 맞추기 위해 노력할 필요가 없다. -1이 들어간 차원의 크기는 다른 차원의 값들을 곱하고 남은 필요한 값이 자동으로 채워지게 됩니다. 다음 코드를 통해 -1의 활용을 확인한다.

In [ ]:
print(x.view(-1))

print(x.view(3, -1))

print(x.view(-1, 1, 4))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


이떄 중요한 점은 view 함수의 결과 텐서 주소는 바뀌지 않는다는 것이다. 따라서 다음 코드에서 y의 값이 바뀐다면 x의 값도 바뀌게 됩니다.

In [ ]:
y = x.view(3,4)

x.storage().data_ptr() == y.storage().data_ptr()

True

파이토치 텐서의 형태를 변환하는 함수는 view 이외에도 여러 함수가 있다. 사실 view 함수는 메모리 순차대로 선언된(contiguous) 텐서에 대해서만 동작합니다. 만약 해당 조건에 만족하지 않는다면 오류를 발생시킨다.

[error]RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

이런 상황에서 텐서 형태 변환을 진행하고 싶다면 contiguous함수를 호출한 후 view함수를 호출하면된다. contiguous 함수는 텐서를 새로운 메모리상의 인접한 주소에 인접한 값을 순서대로 할당해주는 함수입니다. 이미 메모리상에 원하는 형태로 존재한다면 새롭게 할당하지 않고 해당 텐서를 contiguous 함수의 결과값으로 그대로 반환합니다. 또는 오류 메시지에 써져 있는대로 reshape 함수를 활용할 수 있다. reshape 함수는 view 함수와 동일하게 동작하되 contiguous 함수와 view 함수를 순차적으로 호출한 것과 같다.

In [ ]:
print(x.reshape(3,4))

# reshape는 contiguous 함수도 함께 호출한 것이기 때문에 결과 텐서의 주소가 이전 텐서와 다를 수 있다는 것에 유의하라.

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


### 2. Squeeze 함수

Squeeze 함수는 차원의 크기가 1인 차원을 없애주는 역할을 합니다.

In [ ]:
x = torch.FloatTensor([[[1,2],
                        [3,4]]])
print(x.size())

print(x.squeeze(), x.squeeze().size())

torch.Size([1, 2, 2])
tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])


### 3. Unsqueeze 함수
squeeze의 반대 역할을 수행하는 함수이다. 지정된 차원의 인덱스의 차원의 크기가 1인 차원을 삽입한다.

In [ ]:
x = torch.FloatTensor([[1,2],
                        [3,4]])
print(x.size()) # [2,2] 행렬

print(x.unsqueeze(1))

print(x.unsqueeze(1).size())

# print(x.unsqueeze(-1), x.unsqueeze(-1).size())

# print(x.unsqueeze(2), x.unsqueeze(2).size())

torch.Size([2, 2])
tensor([[[1., 2.]],

        [[3., 4.]]])
torch.Size([2, 1, 2])


## 3.6 텐서 자르기 & 붙이기

### 1. 인덱싱과 슬라이싱

In [ ]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])

print(x.size())

torch.Size([3, 2, 2])


In [ ]:
# 첫 번째 차원의 0번 인덱스만 슬라이싱하기

print(x[0])

# 뒤에서 첫 번째 차원의 인덱스만 슬라이싱하기

print(x[-1])

# 중간 차원에 대해서 슬라이싱하기

print(x[:, 0])

# 첫 번째 차원에서 인덱스 1 이상부터 2 이전까지의 부분을,
# 두 번째 차원에서는 1 이상부터의 부분을 마지막 차원에서는 전부를 가져왔을 때의 크기를 반환

print(x[1:2, 1:, :].size())

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
torch.Size([1, 1, 2])


### 2. Split 함수
텐서를 특정 차원에 대해서 원하는 크기로 잘라준다.

In [ ]:
x = torch.FloatTensor(10, 4)

splits = x.split(4, dim=0)

for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


### 3. Chunk 함수
split 함수는 개수에 상관 없이 원하는 크기로 나누었다면 크기에 상관 없이 원하는 개수로 나누는 기능을 가진건 Chunk이다.

In [ ]:
x = torch.FloatTensor(8, 4)

chunks = x.chunk(3, dim = 0)

for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


### 4. Index Select 함수
특정 차원에서 원하는 인덱스의 값만 취하는 함수

In [ ]:
x = torch.FloatTensor([[[1,1],
                        [2,2]],
                       [[3,3],
                        [4,5]],
                       [[5,5],
                        [6,6]]])

indice = torch.LongTensor([2,1])
print(x.size())

torch.Size([3, 2, 2])


In [ ]:
y = x.index_select(dim=0, index = indice)
print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 5.]]])
torch.Size([2, 2, 2])


### 5. Concatenate 함수
하나의 텐서가 아닌 여러 텐서를 하나의 텐서로 합치는 방법이다. 배열내의 두 개 이상의 텐서를 순서대로 합쳐서 하나의 텐서로 반환합니다. 물론 합쳐지기 위해서는 다른 차원들의 크기가 같아야한다.

In [ ]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

y = torch.FloatTensor([[10,11,12],
                       [13,14,15],
                       [16,17,18]])

print(x.size(), y.size())

z = torch.cat([x,y], dim=0)

print(z)

print(z.size())

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [ ]:
z = torch.cat([x,y], dim=-1) # 마지막 차원으로 텐서를 이어 붙이기

print(z)

print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


### 6. Stack 함수
cat 함수와 비슷한 역할을 수행하지만 이어 붙이는 작업이 아닌 쌓는 작업을 수행한다.

In [ ]:
z = torch.stack([x,y])
print(z)

print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [ ]:
z = torch.stack([x,y], dim=-1)

print(z)

print(z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


stack  함수는 새로운 차원을 만든 뒤에 cat 함수를 수행한 것과 같다. unsqueeze 함수와 cat 함수를 써서 똑같이 구현이 가능하다.

In [ ]:
d = 0
z = torch.cat([x.unsqueeze(d), y.unsqueeze(d)], dim = d)

print(z)

print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


### 7. 유용한 팁
cat 함수나 stack 함수는 실전에서 매우 유용하게 활용될 때가 많다. 특히 여러 이터레이션을 돌며 반복되는 작업을 수행한 후 반복 작업의 결과물을 하나로 합치는데 사용된다.

In [ ]:
result = [] # 빈 리스트 생성

for i in range(5):
    x = torch.FloatTensor(2,2)
    result += [x]
    
result = torch.stack(result)
result

tensor([[[1.3180e-33, 0.0000e+00],
         [3.3631e-44, 0.0000e+00]],

        [[1.3039e-33, 0.0000e+00],
         [3.9236e-44, 0.0000e+00]],

        [[1.3039e-33, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[1.3041e-33, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[1.3040e-33, 0.0000e+00],
         [1.3372e-33, 0.0000e+00]]])

## 3.7 유용한 함수들

### 1. Expand 함수
expand 함수는 차원의 크기가 1인 차원을 원하는 크기로 늘려주는 함수

In [ ]:
x = torch.FloatTensor([[[1,2]],
                      [[3,4]]])

print(x.size())

torch.Size([2, 1, 2])


In [ ]:
y = x.expand(2,3,2)

print(y)

print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### 2. Random Permutation 함수
randperm 함수는 랜덤 수열을 생성하는 파이토치 함수이다. 딥러닝은 랜덤성에 의존하는 부분이 많기 때문에 필요에 따라 이 함수를 활용할 수 있다. 다음 코드에서 볼 수 있듯이 randperm 함수의 인자로 숫자를 넣어주면 1부터 해당 숫자까지의 정수를 임의로 순서로 텐서에 넣어 반환합니다.

In [ ]:
x = torch.randperm(10)
print(x)

tensor([8, 6, 4, 2, 5, 9, 1, 3, 0, 7])


### 3. Argument Max 함수
argmax 함수는 수식에서도 많이 활용된다. set X에서 뽑을 수 있는 x 값 중에 함수 f의 출력값을 최대로 만드는 입력을 반환하는 함수입니다. 중요한 점은 f의 최댓값을 반환하는 것이 아니라 f를 최대로 만드는 x값을 반환한다는 것이다. 

In [ ]:
x = torch.randperm(3**3).reshape(3,3,-1)

print(x)

y = x.argmax(dim=-1)
print(y)

tensor([[[ 7, 22, 19],
         [ 3,  8, 25],
         [ 2,  6, 15]],

        [[ 0, 20,  1],
         [12, 18,  5],
         [11, 13, 14]],

        [[ 4, 21, 16],
         [ 9, 23, 24],
         [10, 17, 26]]])
tensor([[1, 2, 2],
        [1, 1, 2],
        [1, 2, 2]])


### 4. Top-k 함수
이번에는 argmax의 상위 호환 버젼인 topk이다. 앞의 argmax는 가장 큰 한 개의 값의 인덱스를 반환하는 것이었다면 topk 함수는 가장 큰 k개의 값과 인덱스를 모두 반환한다.

In [ ]:
values, indices = torch.topk(x, k = 1, dim = -1)
print(values.size())

print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


topk 함수는 상위 kr개 값과 인덱스를 모두 반환하기 때문에 반환 값을 튜플로 받는다. 현재는 k = 1이므로 values, indices의 마지막 차원의 크기가 1로 되어있다. 만약 k를 1보다 더 큰 값을 쓸 경우 반환되는 텐서의 크기는 다음과 같다.

In [ ]:
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size())

torch.Size([3, 3, 2])


### 5. Sort 함수
앞서 선언한 텐서 x를 원하는 차원 기준으로 정렬 후 k개를 뽑아오는 함수이다.

In [ ]:
t = -1
values, indices = torch.topk(x, k = x.size(t), largest = True) # 결과물 내림차순 정렬

print(values)

tensor([[[22, 19,  7],
         [25,  8,  3],
         [15,  6,  2]],

        [[20,  1,  0],
         [18, 12,  5],
         [14, 13, 11]],

        [[21, 16,  4],
         [24, 23,  9],
         [26, 17, 10]]])


### 6. Masked Fill 함수
텐서 내의 원하는 부분만 특정 값으로 바꿔치기하는 함수인 masked_fill

In [ ]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3,-1)
print(x)

print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [ ]:
mask = x > 4
print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


### 7. Ones & Zeros 함수
ones 함수와 zeros 함수를 통해 쉽게 구현할 수 있습니다 

In [ ]:
print(torch.ones(2,3))

print(torch.zeros(2,3))

# ones_like와 zeros_like

x = torch.FloatTensor([[1,2,3],
                      [4,5,6]])

print(torch.ones_like(x))

print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
