## 6.1 미분이란

### 1. 기울기
- 기울기는 x 증가량에 대한 y 증가량으로 정의된다

### 2. 극한과 미분
- x의 변화량이 매우 작을 때 y의 변화량 또한 구할 수 있을 것이다.
- 앞에서는 두 점 사이의 기울기였지만 지금은 함수 $f$ 위의 지점 (x, f(x))에서의 접섭의 기울기라고 볼 수 있다.

### 3. 도함수
- $$g(x) = \lim_{h->0}^n \frac{f(x+h-f(x)}{(x+h)-x}$$
- 이때 함수 $f$의 기울기를 함수로 나태난 g를 도함수라고 부르며 함수 $f$를 미분하여 얻을 수 있습니다.

### 4. 뉴턴 vs 라이프니츠
- 미분 표기법 중 작은 따옴표를 붙여 사용하는 방법은 뉴턴의 표기법이고 델타를 사용하여 분수처럼 표기하는 방법은 라이프니츠의 표기법이다.
- 여러 개의 변수가 주어진 상황에서는 라이프니츠 방식의 미분 표기법이 훨씬 더 직관적으로 표현되는 것을 알 수 있다.

## 6.2 편미분

### 1. 편미분
- 함수의 변수 중 하나의 입력 변수에 대해서만 미분을 수행하는 것을 편미분이라고 한다.
- 다 변수 함수 $f$에서 특정 지점 (x,y)의 기울기는 각 변수별 미분 결과를 합쳐서 벡터로 나타내게 된다. 1치원 함수에서의 미분 결과는 기울기의 스칼라 값이지만, 다변수 함수에서의 미분 결과는 입력 변수 개수만큼의 차원을 갖는 벡터가 됩니다.

### 2. 함수의 입출력 형태

벡터를 입력으로 받는 함수
- 다변수 함수는 벡터를 입력으로 받는 것이라고 생각할 수있다. 따라서 다음 수식처럼 n차원의 벡터 x를 입력으로 받는 함수라고 볼 수 있다.
- $y = f(\begin{bmatrix}x_1 \\ \vdots \\ x_n \end{bmatrix}) = f(x),$
- $where X \in \mathbb{R}^n$

행렬을 입력으로 받는 함수
- $y = f\begin{bmatrix}
x_{1,1} & \cdots & x_{1,m} \\
\vdots & \ddots & \vdots \\
x_{n,1}& \cdots & x_{n,m}
\end{bmatrix}) = f(X),$
- $where X \in \mathbb{R}^{n*m}$

출력이 벡터 또는 행렬인 함수
- 출력이 벡터이거나 행렬인 함수 형태도 생각해 볼 수 있다. 다음 수식은 각각 출력이 n차원의 벡터이거나, n*m 차원의 행렬인 경우를 보여준다.
- $y = f(\begin{bmatrix}y_1 \\ \vdots \\ y_n \end{bmatrix}) = f(x),$
- $where X \in \mathbb{R}^n$

- $Y = f\begin{bmatrix}
y_{1,1} & \cdots & y_{1,m} \\
\vdots & \ddots & \vdots \\
y_{n,1}& \cdots & y_{n,m}
\end{bmatrix}) = f(x),$
- $where X \in \mathbb{R}^{n*m}$

입력과 출력이 벡터인 함수
- 입력과 출력이 벡터이거나 행렬인 함수도 생각해볼 수 있을 것입니다. 다음 수식은 입력과 출력이 각각 n차원과 m차원인 함수를 수식으로 표현한 것입니다.
- n개의 입력을 받아 m개의 출력을 내보내는 선형 계층도 여기에 속한다.
- $y = f(\begin{bmatrix}y_1 \\ \vdots \\ y_n \end{bmatrix}) = f(x) = 
f(\begin{bmatrix}x_1 \\ \vdots \\ x_n \end{bmatrix}),$
- $where X \in \mathbb{R}^n \rightarrow \mathbb{R}^m$

### 3. 행렬의 미분

스칼라를 벡터로 미분
- ${\partial f \over \partial x} = \bigtriangledown , x^f = \begin{bmatrix}\partial f \over \partial x_1 \\ \vdots \\ \partial f \over \partial x_n \end{bmatrix}$
- $where x \in \mathbb{R}^{n}$

스칼라를 행렬로 미분
- ${\partial f \over \partial X} = \bigtriangledown , x^f = \begin{bmatrix}
{\partial f \over \partial x_{1,1}} & \cdots & {\partial f \over \partial x_{1,m}} \\
\vdots & \ddots & \vdots \\
{\partial f \over \partial x_{n,1}} & \cdots & {\partial f \over \partial x_{n,m}} \end{bmatrix}$
- $where x \in \mathbb{R}^{n*m}$

벡터를 스칼라로 미분
- ${\partial f \over \partial x} = \begin{bmatrix}\partial f_{1} \over \partial x & \cdots & \partial f_{n} \over \partial x \end{bmatrix}$
- $where x \in \mathbb{R}^{n}$

벡터를 벡터로 미분
- ${\partial f \over \partial x} = \begin{bmatrix}\partial f \over \partial x_1 \\ \vdots \\ \partial f \over \partial x_n \end{bmatrix} = \begin{bmatrix}\partial f_{1} \over \partial x & \cdots & \partial f_{n} \over \partial x \end{bmatrix} = \begin{bmatrix}
{\partial f_{1} \over \partial x_{1}} & \cdots & {\partial f_{m}ㅡ \over \partial x_{1}} \\
\vdots & \ddots & \vdots \\
{\partial f_{1} \over \partial x_{n}} & \cdots & {\partial f_{m} \over \partial x_{n}} \end{bmatrix}$
- $where x \in \mathbb{R}^{n} and f(x) \in \mathbb{R}^{m}$


## 6.3 경사하강법
- 효율적으로 손실 함수의 출력을 최소로 만드는 입력을 찾기 위한 방법

### 1. 1차원에서의 경사하강법
- 경사하강법은 미분 가능한 복잡한 함수가 있을 때 해당 함수의 최소점을 찾기 위한 방법이다.

### 2. 경사하강법의 수식 표현
- $x \leftarrow x - \boldsymbol{\eta}*{df \over dx}$
- $where y = f(x)$
- 함수 $f$의 출력값 y를 미분하면 각 지점에 대한 기울기를 구할 수 있다.
- 그다음 움직여야 하는 다음 지점의 위치는 현재 지점의 기울기를 빼주면 구할 수 있다.

### 3. 전역 최소점과 지역 최소점
- 손실 함수를 대입하면 손실 값이 최소가 되는 모델의 가중치 파라미터가 되는 점을 전역 최소점이라고 한다.
- 이와 반대로 전역 최소점은 아니지만 하강 구간에 존재하는 가장 낮은 부분을 지역 최소적이라고 한다.

### 4. 다차원으로 확장
- 앞 예제들은 1차원 함수 위에서의 경사하강법에 대한 언급이었다. 이제부터는 2차원 벡터를 입력으로 받는 함수에 대하여 생각해본다.
- $y = f(x) = f(\begin{bmatrix}x_1 \\ x_n \end{bmatrix}), where \in \mathbb{R}^{2}$
- 결과저으로 우리는 다음 x를 $x \leftarrow x - \boldsymbol{\eta}*\nabla x_{f}$ 다음과 같이 업데이트할 수 있습니다.

### 5. 모델 가중치 파라미터 확장
- 모델 함수의 가중치 파라미터에 대해서도 문제를 확장해볼 수 있습니다. 모델 함수가 선형 계층 함수로 구성되어 있다고 가정한다면 가중치 파라미터를 다음과 같이 정의할 수 있을 것이다.

- $f_{𝛩}(x) = x*W + b, and \ θ = {W, b}$,
- $where W \in \mathbb{R}^{n*m} and \ b \in \mathbb{R}^{m}$
- 수식에서 보이듯이 n * (m+1) 차원의 공간에서 최적의 가중치 파라미터를 찾아야한다. 이를 위해 각 가중치 파라미터 W와 b로 손실 함수를 미분하여 그레디언트를 구하고 파라미터들을 업데이트 할 수 있다.

딥러닝에서 지역 최소점 문제
- 여러 계층을 쌓는 심층신경망을 모델로 활용한다면 가중치 파라미터는 커질 수 밖에 없다. 다만 높은 차원에서 지역 최소점이 큰 문제가 되지 않는다는 것이 학계의 중론이다. 지역 최소점에 빠지더라고 그 점은 아마도 경험적으로 전역 최소점의 근방에 위치할 것이라는 말도 존재한다. 이것은 지역 최소점을 구성하기 위한 조건들이 높은 차원에서는 만족되기 어렵기 때문이다.

## 6.4 학습률에 따른 성질
- $Θ ← - η*{\partial \mathcal{L(Θ)} \over dx}$
- 학습률은 η(에타) 기호로 표시되며 보통 0에서 1사이의 값을 가진다. 기울기 벡터인 그레디언트에 곱해지는 된다. 따라서 가중치 파라미터가 업데이트 될 때 기울기의 값을 얼마큼 반영할 것인지 설정하는 것이라고 볼 수 있다.  
- 만약 학습률이 너쿠 커서 손실 값이 발산하는 상황이라면 학습률을 50% 또는 10%로 줄려주는 것이 좋다

## 6.5 경사하강법 구현
- 경사하강법을 통해 랜덤하게 생성한 텐서가 특정 텐서 값을 근사 계산하도록 파이토치를 구현해본다. 여기에서 함수의 출력은 목표 텐서와 랜덤 텐서 사이의 차이가 될 것이도 함수의 입력은 랜덤 생성한 텐서의 현재 값이 된다. 따라서 랜덤 생성한 텐의 값을 경사하강법을 활용하여 이리저리 바꿔가며 함수의 출력값을 최소화해보도록 하겠다.

In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [3]:
# requires_grad 속성 True
x = torch.rand_like(target)

x.requires_grad = True

print(x)

tensor([[0.5585, 0.2163, 0.8081],
        [0.1720, 0.2202, 0.3436],
        [0.4047, 0.6718, 0.8780]], requires_grad=True)


In [4]:
# 텐서의 손실 값 계산

loss = F.mse_loss(x, target)

loss

tensor(0.0854, grad_fn=<MseLossBackward0>)

In [8]:
# while문을 사용한 경사 하강법

threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    loss.backward() # 기울기 계산

    x = x - learning_rate * x.grad

    x.detach_()
    x.requires_grad_(True)

    loss = F.mse_loss(x, target)

    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

## 6.6 파이토치 오토그래드 소개

- 파이토치에는 자동 미분 기능을 제공한다. 토치는 requires_grad 속성이 True인 텐서의 연산을 추적하기 위한 계산 그래프를 구축하고, backward 함수가 호출되면 이 그래프를 따라 미분을 자동으로 수행한다.

In [15]:
x = torch.FloatTensor([[1,2],
                       [3,4]]).requires_grad_(True)

In [16]:
x1 = x + 2
print(x1)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)


In [17]:
x2 = x - 2
print(x2)

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)


In [18]:
x3 = x1 * x2
print(x3)

tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)


In [19]:
y = x3.sum()
print(y)

tensor(14., grad_fn=<SumBackward0>)


코드의 결과를 보면 모두 grad_fn이라는 속성을 가진다. 예를 들어 텐서 x1이 덧셈 연산의 결과물이기 때문에 x1의 grad_fn 속성은 AddBackward0이다. 텐서 y는 sum 함수를 쓰므로 스칼라 값이 되었다. 그럼 여기에서 backward 함수를 호출해본다.

In [20]:
y.backward()

x, x1, x2, x3, y 모두 grad 속성에 저장되어있다. 수식으로 나타내면 다음과 같다.

- $x = \begin{bmatrix}x_{1,1} & x_{1,2} & \\ x_{2,1} & x_{2,2} \end{bmatrix}$
- $x_1 = x + 2$, $x_2 = x - 2$, $x_3 = x_1 * x_2$
- $y = sum(x_3) = x_{3(1,1)}, x_{3(1,2)}, x_{3(2,1)}, x_{3(2,2)}$ 이렇게 구한 y를 다시 x로 미분하면 ${dy \over dx} = 2x$


In [21]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


## 6.7 마치며

### 요약

1. 경사하강법이 필요한 이유
 - 신경망의 내부 가중치 파라미터를 잘 조절하여 원하는 함수를 근사계산하고 싶을 때 할용할 수 있다.
 - 손실 함수를 통해 더 좋은 가중치를 파라미터를 선택할 수 있다.
 - 효율적으로 가중치 파라미터를 찾고 싶을 때 사용
 - 손실 값을 가중치 파라미터로 미분하여 그래디언트 벡터를 구하고 반대 방향으로 가중치 파라미터를 업데이트하면 점진적으로 더 낮은 손실 값을 갖는 가중치 파라미터를 구할 수 있다.

2. 학습률
 - 학습률이 너무 클 경우 : 파라미터 업데이트 과정에서 손실 값이 발산할 수 있다.
 - 학습률이 너무 작을 경우 : 파라미터가 너무 조금씩 바뀌어서 학습이 느려진다.

3. 오토그래드
 - 파이토치는 오토그래드 알고리즘을 통해 미분을 자동으로 수행할 수 있다.
 - 스칼라 값에 backward 함수를 호출하여 자동 미분을 수행
 - 텐서간의 연산마다 계산 그래프를 자동으로 생성하고 나중에 미분할 때 활용